### ISSUE TITLE
I cannot click the button...

### ISSUE THREAD

**Issue by izhangxb** [spacecowboy/AndroidCodeGenerator#3]
when the codes is too long ,the window cannot  display normally,and I can't click the botton at the bottom.How can I fix it?

**Comment by spacecowboy** [comment]
OK. What button are you talking about?

**Comment by izhangxb** [comment]
"Copy code to clickboard" and "Create File".

**Comment by izhangxb** [comment]
![image](https://cloud.githubusercontent.com/assets/16055554/12252819/89e15c1e-b915-11e5-9893-4711c43c0365.png)

en ,just like this.

**Comment by spacecowboy** [comment]
You have to take that up with Windows and AndroidStudio.

This project is a python script which outputs Java source files.
